name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: go mod tidy
        working-directory: api

      - name: Run Tests
        run: go test ./...
        working-directory: api

  deploy:
    name: Deploy to Render
    needs: [api-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_URL }}
        run: |
          curl "$deploy_url"
